/*
 * VisaFlow Auth Service API
 * Authentication and Authorization API for VisaFlow Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: bilal@visaflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.UserDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InternalUserValidationResponse
 */
public class InternalUserValidationResponseTest {
    private final InternalUserValidationResponse model = new InternalUserValidationResponse();

    /**
     * Model tests for InternalUserValidationResponse
     */
    @Test
    public void testInternalUserValidationResponse() {
        // TODO: test InternalUserValidationResponse
    }

    /**
     * Test the property 'valid'
     */
    @Test
    public void validTest() {
        // TODO: test valid
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'hasRequiredRoles'
     */
    @Test
    public void hasRequiredRolesTest() {
        // TODO: test hasRequiredRoles
    }

    /**
     * Test the property 'hasRequiredPermissions'
     */
    @Test
    public void hasRequiredPermissionsTest() {
        // TODO: test hasRequiredPermissions
    }

}
