/*
 * VisaFlow Auth Service API
 * Authentication and Authorization API for VisaFlow Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: bilal@visaflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InternalUserValidationRequest
 */
public class InternalUserValidationRequestTest {
    private final InternalUserValidationRequest model = new InternalUserValidationRequest();

    /**
     * Model tests for InternalUserValidationRequest
     */
    @Test
    public void testInternalUserValidationRequest() {
        // TODO: test InternalUserValidationRequest
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'requiredRoles'
     */
    @Test
    public void requiredRolesTest() {
        // TODO: test requiredRoles
    }

    /**
     * Test the property 'requiredPermissions'
     */
    @Test
    public void requiredPermissionsTest() {
        // TODO: test requiredPermissions
    }

}
