package com.visaflow.modules.document.entity.enums;

public enum DocumentType {
    PASSPORT, BIRTH_CERTIFICATE, BANK_STATEMENT, EMPLOYMENT_LETTER, INVITATION_LETTER,
    TRAVEL_HISTORY, PHOTO, MEDICAL_CERTIFICATE, POLICE_CLEARANCE, TAX_RETURNS,
    MARRIAGE_CERTIFICATE, EDUCATIONAL_CERTIFICATE, OTHER
}
