/*
 * VisaFlow Auth Service API
 * Authentication and Authorization API for VisaFlow Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: bilal@visaflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ChangePasswordRequest;
import org.openapitools.client.model.ForgotPassword200Response;
import org.openapitools.client.model.ForgotPasswordRequest;
import org.openapitools.client.model.ResetPasswordRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PasswordManagementApi
 */
@Disabled
public class PasswordManagementApiTest {

    private final PasswordManagementApi api = new PasswordManagementApi();

    /**
     * Change password (authenticated user)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void changePasswordTest() throws ApiException {
        ChangePasswordRequest changePasswordRequest = null;
        api.changePassword(changePasswordRequest);
        // TODO: test validations
    }

    /**
     * Request password reset link
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void forgotPasswordTest() throws ApiException {
        ForgotPasswordRequest forgotPasswordRequest = null;
        ForgotPassword200Response response = api.forgotPassword(forgotPasswordRequest);
        // TODO: test validations
    }

    /**
     * Reset password using token
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void resetPasswordTest() throws ApiException {
        ResetPasswordRequest resetPasswordRequest = null;
        api.resetPassword(resetPasswordRequest);
        // TODO: test validations
    }

}
