/*
 * VisaFlow Auth Service API
 * Authentication and Authorization API for VisaFlow Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: bilal@visaflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.UpdateCurrentUserRequest;
import org.openapitools.client.model.UserDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserManagementApi
 */
@Disabled
public class UserManagementApiTest {

    private final UserManagementApi api = new UserManagementApi();

    /**
     * Get current user profile
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getCurrentUserTest() throws ApiException {
        UserDTO response = api.getCurrentUser();
        // TODO: test validations
    }

    /**
     * Update current user profile
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateCurrentUserTest() throws ApiException {
        UpdateCurrentUserRequest updateCurrentUserRequest = null;
        UserDTO response = api.updateCurrentUser(updateCurrentUserRequest);
        // TODO: test validations
    }

}
