/*
 * VisaFlow Auth Service API
 * Authentication and Authorization API for VisaFlow Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: bilal@visaflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AuthResponse;
import org.openapitools.client.model.ErrorResponse;
import org.openapitools.client.model.LoginRequest;
import org.openapitools.client.model.Logout200Response;
import org.openapitools.client.model.RefreshToken200Response;
import org.openapitools.client.model.RefreshTokenRequest;
import org.openapitools.client.model.RegisterRequest;
import org.openapitools.client.model.VerifyEmailRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticationApi
 */
@Disabled
public class AuthenticationApiTest {

    private final AuthenticationApi api = new AuthenticationApi();

    /**
     * Authenticate user and get tokens
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void loginTest() throws ApiException {
        LoginRequest loginRequest = null;
        AuthResponse response = api.login(loginRequest);
        // TODO: test validations
    }

    /**
     * Logout user (invalidate refresh token)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void logoutTest() throws ApiException {
        RefreshTokenRequest refreshTokenRequest = null;
        Logout200Response response = api.logout(refreshTokenRequest);
        // TODO: test validations
    }

    /**
     * Get new access token using refresh token
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void refreshTokenTest() throws ApiException {
        RefreshTokenRequest refreshTokenRequest = null;
        RefreshToken200Response response = api.refreshToken(refreshTokenRequest);
        // TODO: test validations
    }

    /**
     * Register new user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void registerTest() throws ApiException {
        RegisterRequest registerRequest = null;
        AuthResponse response = api.register(registerRequest);
        // TODO: test validations
    }

    /**
     * Resend email verification link
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void resendVerificationTest() throws ApiException {
        api.resendVerification();
        // TODO: test validations
    }

    /**
     * Verify user email address
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyEmailTest() throws ApiException {
        VerifyEmailRequest verifyEmailRequest = null;
        api.verifyEmail(verifyEmailRequest);
        // TODO: test validations
    }

}
