/*
 * VisaFlow Auth Service API
 * Authentication and Authorization API for VisaFlow Platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: bilal@visaflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.InternalUserValidationRequest;
import org.openapitools.client.model.InternalUserValidationResponse;
import java.util.UUID;
import org.openapitools.client.model.UserDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InternalApi
 */
@Disabled
public class InternalApiTest {

    private final InternalApi api = new InternalApi();

    /**
     * Get user by ID (internal)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserByIdInternalTest() throws ApiException {
        String xAPIKey = null;
        UUID userId = null;
        UserDTO response = api.getUserByIdInternal(xAPIKey, userId);
        // TODO: test validations
    }

    /**
     * Validate user and permissions (internal use only)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void validateUserInternalTest() throws ApiException {
        String xAPIKey = null;
        InternalUserValidationRequest internalUserValidationRequest = null;
        InternalUserValidationResponse response = api.validateUserInternal(xAPIKey, internalUserValidationRequest);
        // TODO: test validations
    }

}
